// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://fm4rd6aizfhmbhop73s45r2h4i.appsync-api.us-west-2.amazonaws.com/graphql',
          region: 'us-west-2',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-apegeouguzap3bibhsxtsz5sse'
        }
    }
};

export default config;